# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('area', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'vw_city_area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HouseCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('en', models.CharField(blank=True, max_length=500, null=True)),
                ('cn', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'house_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HouseForSale',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('mlsno', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('stno', models.CharField(blank=True, max_length=100, null=True)),
                ('stname', models.CharField(blank=True, max_length=100, null=True)),
                ('sttype', models.CharField(blank=True, max_length=100, null=True)),
                ('aptno', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('askprice', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('inputdate', models.DateField(blank=True, null=True)),
                ('soldprice', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('solddate', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('style', models.CharField(blank=True, max_length=100, null=True)),
                ('bdrm', models.IntegerField(blank=True, null=True)),
                ('wshrm', models.IntegerField(blank=True, null=True)),
                ('maint', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'house_for_sale',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HouseSold',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('mlsno', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('stno', models.CharField(blank=True, max_length=100, null=True)),
                ('stname', models.CharField(blank=True, max_length=100, null=True)),
                ('sttype', models.CharField(blank=True, max_length=100, null=True)),
                ('aptno', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('askprice', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('inputdate', models.DateField(blank=True, null=True)),
                ('soldprice', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('solddate', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('style', models.CharField(blank=True, max_length=100, null=True)),
                ('bdrm', models.IntegerField(blank=True, null=True)),
                ('wshrm', models.IntegerField(blank=True, null=True)),
                ('maint', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'house_sold',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SoldSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=1000, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=1000, null=True)),
                ('year', models.FloatField(blank=True, null=True)),
                ('month', models.FloatField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
                ('prices', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vw_sum_sold',
                'managed': False,
            },
        ),
    ]
